package scanner

import (
	"context"
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/opencleaner/opencleaner/internal/rules"
	"github.com/opencleaner/opencleaner/pkg/types"
)

type NodeScanner struct {
	home      string
	scanRoots []string
}

func NewNodeScanner(home string, scanRoots []string) *NodeScanner {
	return &NodeScanner{home: home, scanRoots: scanRoots}
}

func (s *NodeScanner) ID() string               { return "nodejs" }
func (s *NodeScanner) Name() string              { return "Node.js" }
func (s *NodeScanner) Category() types.Category  { return types.CategoryDeveloper }

func (s *NodeScanner) Scan(ctx context.Context) ([]rules.Rule, error) {
	var mu sync.Mutex
	var found []rules.Rule

	// Discover node_modules directories via bounded walk.
	err := Walk(ctx, WalkConfig{
		RootDirs:   s.scanRoots,
		TargetName: "node_modules",
		MaxDepth:   8,
		SkipHidden: true,
		OnMatch: func(path string) {
			id := "nodejs-node-modules-" + pathHash(path)
			rel := shortPath(s.home, path)
			mu.Lock()
			found = append(found, rules.Rule{
				ID:         id,
				Name:       "node_modules (" + rel + ")",
				Path:       path,
				Category:   types.CategoryDeveloper,
				Safety:     types.SafetySafe,
				SafetyNote: "Regenerated by npm/yarn/pnpm install",
				Desc:       "Node.js dependency directory",
			})
			mu.Unlock()
		},
	})
	if err != nil {
		return found, err
	}

	// Known cache paths — use same IDs as builtins for dedup.
	knownPaths := []struct {
		id, name, path, note string
	}{
		{"npm-cache", "npm cache", filepath.Join(s.home, ".npm", "_cacache"), "npm download cache"},
		{"yarn-cache", "Yarn cache", filepath.Join(s.home, "Library", "Caches", "Yarn"), "Yarn v1 cache"},
		{"nodejs-yarn-berry-cache", "Yarn Berry cache", filepath.Join(s.home, ".yarn", "berry", "cache"), "Yarn Berry (v2+) cache"},
		{"nodejs-pnpm-store", "pnpm store", filepath.Join(s.home, "Library", "pnpm", "store"), "pnpm content-addressable store"},
	}
	for _, kp := range knownPaths {
		if _, err := os.Lstat(kp.path); err != nil {
			continue
		}
		found = append(found, rules.Rule{
			ID:         kp.id,
			Name:       kp.name,
			Path:       kp.path,
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Download cache; regenerated on next install",
			Desc:       kp.note,
		})
	}

	return found, nil
}

func pathHash(p string) string {
	h := sha256.Sum256([]byte(p))
	return fmt.Sprintf("%x", h[:4])
}

func shortPath(home, p string) string {
	if rel, err := filepath.Rel(home, p); err == nil && !strings.HasPrefix(rel, "..") {
		return "~/" + rel
	}
	return p
}
