package scanner

import (
	"context"
	"os"
	"path/filepath"
	"sync"

	"github.com/opencleaner/opencleaner/internal/rules"
	"github.com/opencleaner/opencleaner/pkg/types"
)

type PythonScanner struct {
	home      string
	scanRoots []string
}

func NewPythonScanner(home string, scanRoots []string) *PythonScanner {
	return &PythonScanner{home: home, scanRoots: scanRoots}
}

func (s *PythonScanner) ID() string               { return "python" }
func (s *PythonScanner) Name() string              { return "Python" }
func (s *PythonScanner) Category() types.Category  { return types.CategoryDeveloper }

func (s *PythonScanner) Scan(ctx context.Context) ([]rules.Rule, error) {
	var mu sync.Mutex
	var found []rules.Rule

	// Discover __pycache__ directories.
	_ = Walk(ctx, WalkConfig{
		RootDirs:   s.scanRoots,
		TargetName: "__pycache__",
		MaxDepth:   10,
		SkipHidden: true,
		OnMatch: func(path string) {
			id := "python-pycache-" + pathHash(path)
			mu.Lock()
			found = append(found, rules.Rule{
				ID:         id,
				Name:       "__pycache__ (" + shortPath(s.home, path) + ")",
				Path:       path,
				Category:   types.CategoryDeveloper,
				Safety:     types.SafetySafe,
				SafetyNote: "Auto-regenerated by Python on next import",
				Desc:       "Python bytecode cache",
			})
			mu.Unlock()
		},
	})

	// Discover .venv directories (SkipHidden=false to find dot-prefixed dirs).
	_ = Walk(ctx, WalkConfig{
		RootDirs:   s.scanRoots,
		TargetName: ".venv",
		MaxDepth:   6,
		SkipHidden: false,
		OnMatch: func(path string) {
			if !isVirtualenv(path) {
				return
			}
			id := "python-venv-" + pathHash(path)
			mu.Lock()
			found = append(found, rules.Rule{
				ID:         id,
				Name:       ".venv (" + shortPath(s.home, path) + ")",
				Path:       path,
				Category:   types.CategoryDeveloper,
				Safety:     types.SafetyModerate,
				SafetyNote: "Virtual environment; recreate with python -m venv",
				Desc:       "Python virtual environment",
			})
			mu.Unlock()
		},
	})

	// Discover venv/ directories (only if they contain pyvenv.cfg).
	_ = Walk(ctx, WalkConfig{
		RootDirs:   s.scanRoots,
		TargetName: "venv",
		MaxDepth:   6,
		SkipHidden: true,
		OnMatch: func(path string) {
			if !isVirtualenv(path) {
				return
			}
			id := "python-virtualenv-" + pathHash(path)
			mu.Lock()
			found = append(found, rules.Rule{
				ID:         id,
				Name:       "venv (" + shortPath(s.home, path) + ")",
				Path:       path,
				Category:   types.CategoryDeveloper,
				Safety:     types.SafetyModerate,
				SafetyNote: "Virtual environment; recreate with python -m venv",
				Desc:       "Python virtual environment",
			})
			mu.Unlock()
		},
	})

	// Known cache path.
	pipCache := filepath.Join(s.home, "Library", "Caches", "pip")
	if _, err := os.Lstat(pipCache); err == nil {
		found = append(found, rules.Rule{
			ID:         "python-pip-cache",
			Name:       "pip cache",
			Path:       pipCache,
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Download cache; pip re-downloads as needed",
			Desc:       "pip package download cache",
		})
	}

	return found, nil
}

// isVirtualenv checks if the directory is a Python virtual environment
// by looking for pyvenv.cfg inside it.
func isVirtualenv(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, "pyvenv.cfg"))
	return err == nil
}
