package scanner

import (
	"context"
	"os"
	"path/filepath"
	"sync"

	"github.com/opencleaner/opencleaner/internal/rules"
	"github.com/opencleaner/opencleaner/pkg/types"
)

type RustScanner struct {
	home      string
	scanRoots []string
}

func NewRustScanner(home string, scanRoots []string) *RustScanner {
	return &RustScanner{home: home, scanRoots: scanRoots}
}

func (s *RustScanner) ID() string               { return "rust" }
func (s *RustScanner) Name() string              { return "Rust" }
func (s *RustScanner) Category() types.Category  { return types.CategoryDeveloper }

func (s *RustScanner) Scan(ctx context.Context) ([]rules.Rule, error) {
	var mu sync.Mutex
	var found []rules.Rule

	// Discover target/ directories that have a Cargo.toml sibling.
	_ = Walk(ctx, WalkConfig{
		RootDirs:   s.scanRoots,
		TargetName: "target",
		MaxDepth:   8,
		SkipHidden: true,
		OnMatch: func(path string) {
			parent := filepath.Dir(path)
			if _, err := os.Stat(filepath.Join(parent, "Cargo.toml")); err != nil {
				return // not a Rust project
			}
			id := "rust-target-" + pathHash(path)
			mu.Lock()
			found = append(found, rules.Rule{
				ID:         id,
				Name:       "target/ (" + shortPath(s.home, path) + ")",
				Path:       path,
				Category:   types.CategoryDeveloper,
				Safety:     types.SafetySafe,
				SafetyNote: "Build artifacts; regenerated by cargo build",
				Desc:       "Rust build output directory",
			})
			mu.Unlock()
		},
	})

	// Known paths — reuse cargo-registry ID for dedup with builtins.
	knownPaths := []struct {
		id, name, path, note, safety string
	}{
		{"cargo-registry", "Cargo registry", filepath.Join(s.home, ".cargo", "registry"), "Crate source cache; cargo re-downloads as needed", "moderate"},
		{"rust-cargo-git", "Cargo git checkouts", filepath.Join(s.home, ".cargo", "git"), "Git dependency checkouts; cargo re-clones as needed", "moderate"},
	}
	for _, kp := range knownPaths {
		if _, err := os.Lstat(kp.path); err != nil {
			continue
		}
		safety := types.SafetyModerate
		if kp.safety == "safe" {
			safety = types.SafetySafe
		}
		found = append(found, rules.Rule{
			ID:         kp.id,
			Name:       kp.name,
			Path:       kp.path,
			Category:   types.CategoryDeveloper,
			Safety:     safety,
			SafetyNote: kp.note,
			Desc:       kp.note,
		})
	}

	return found, nil
}
