package rules

import (
	"path/filepath"

	"github.com/opencleaner/opencleaner/pkg/types"
)

// BuiltinRules is a conservative MVP set. Do NOT add new targets without validating against the PRD and
// clmm-clean-my-mac-cli reference paths.
func BuiltinRules(home string) []Rule {
	p := func(parts ...string) string { return filepath.Join(append([]string{home}, parts...)...) }

	return []Rule{
		// Developer
		{
			ID:         "xcode-derived-data",
			Name:       "Xcode DerivedData",
			Path:       p("Library", "Developer", "Xcode", "DerivedData"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetyModerate,
			SafetyNote: "Xcode will rebuild DerivedData; first build may be slower.",
			Desc:       "Build artifacts and indexes generated by Xcode.",
		},
		{
			ID:         "xcode-archives",
			Name:       "Xcode Archives",
			Path:       p("Library", "Developer", "Xcode", "Archives"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetyModerate,
			SafetyNote: "Deleting archives removes old builds; ensure you don’t need them.",
			Desc:       "Archived builds (Organizer → Archives).",
		},
		{
			ID:         "xcode-device-support",
			Name:       "Xcode Device Support",
			Path:       p("Library", "Developer", "Xcode", "iOS DeviceSupport"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetyModerate,
			SafetyNote: "Xcode may need to re-download symbols for connected devices.",
			Desc:       "Downloaded device symbols and support files for iOS devices.",
		},
		{
			ID:         "simulator-caches",
			Name:       "Simulator Caches",
			Path:       p("Library", "Developer", "CoreSimulator", "Caches"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetyModerate,
			SafetyNote: "Simulators may rebuild caches; first launch may be slower.",
			Desc:       "Caches used by iOS/tvOS/watchOS simulators.",
		},
		{
			ID:         "homebrew-cache",
			Name:       "Homebrew Cache",
			Path:       p("Library", "Caches", "Homebrew"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Safe; Homebrew will re-download bottles as needed.",
			Desc:       "Downloaded bottles and metadata.",
		},
		{
			ID:         "swiftpm-cache",
			Name:       "SwiftPM Cache",
			Path:       p("Library", "Caches", "org.swift.swiftpm"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Safe; packages will be re-fetched as needed.",
			Desc:       "Swift Package Manager download and build caches.",
		},
		{
			ID:         "go-build-cache",
			Name:       "Go Build Cache",
			Path:       p("Library", "Caches", "go-build"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Safe; Go will rebuild the cache.",
			Desc:       "Compiled package cache used by the Go toolchain.",
		},
		{
			ID:         "cocoapods-cache",
			Name:       "CocoaPods Cache",
			Path:       p("Library", "Caches", "CocoaPods"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Safe; pods will be re-downloaded as needed.",
			Desc:       "Cached pod downloads.",
		},
		{
			ID:         "gradle-cache",
			Name:       "Gradle Cache",
			Path:       filepath.Join(home, ".gradle", "caches"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetyModerate,
			SafetyNote: "Gradle will re-download dependencies; next build may be slower.",
			Desc:       "Gradle dependency and build caches.",
		},
		{
			ID:         "cargo-registry",
			Name:       "Cargo Registry Cache",
			Path:       filepath.Join(home, ".cargo", "registry"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetyModerate,
			SafetyNote: "Cargo will re-download crates; next build may be slower.",
			Desc:       "Rust crate downloads and index.",
		},
		{
			ID:         "npm-cache",
			Name:       "npm Cache",
			Path:       p(".npm", "_cacache"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Safe; npm will re-download packages.",
			Desc:       "Content-addressed npm cache.",
		},
		{
			ID:         "yarn-cache",
			Name:       "Yarn Cache",
			Path:       p("Library", "Caches", "Yarn"),
			Category:   types.CategoryDeveloper,
			Safety:     types.SafetySafe,
			SafetyNote: "Safe; Yarn will re-download packages.",
			Desc:       "Yarn download cache.",
		},

		// System
		{
			ID:         "user-library-logs",
			Name:       "User Logs",
			Path:       p("Library", "Logs"),
			Category:   types.CategorySystem,
			Safety:     types.SafetyModerate,
			SafetyNote: "May remove application logs used for troubleshooting.",
			Desc:       "Application and subsystem logs under your user account.",
		},
		{
			ID:         "user-library-caches",
			Name:       "User Caches",
			Path:       p("Library", "Caches"),
			Category:   types.CategorySystem,
			Safety:     types.SafetyModerate,
			SafetyNote: "Apps may re-download data; some apps may require re-login.",
			Desc:       "Per-user cache storage used by many apps.",
		},
	}
}
